name: Build and Package

on:
  push:
    branches:
      - main  # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Adjust the Python version as needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install your Python dependencies

    - name: Build executable
      run: |
        pip install pyinstaller
        pyinstaller --onefile --windowed app.py
        # Add additional commands if necessary to prepare your data files, models, etc.

    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my_application  # Adjust the artifact name as needed
        path: dist/my_application  # Adjust the path to your executable
